import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer';
import Navbar from '../components/Navbar'
import BaseLayout from '../layout/BaseLayout';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <BaseLayout>
      <Head>
        <title>Index Page-game row</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    </BaseLayout>
  );
}
